# Generated by Django 3.0.8 on 2020-07-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Accounts'),
        ),
    ]
