# Generated by Django 3.0.8 on 2020-07-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactions_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
    ]
