# Generated by Django 3.0.8 on 2020-07-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200714_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, choices=[('CR', 'Credit'), ('DT', 'Debit')], max_length=2, null=True),
        ),
    ]
