# Generated by Django 3.0.8 on 2020-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('CR', 'Credit'), ('DT', 'Debit')], default='FK', max_length=2),
            preserve_default=False,
        ),
    ]
