# Generated by Django 3.0.8 on 2020-07-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20200718_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='amount_currency',
            new_name='balance_currency',
        ),
        migrations.RenameField(
            model_name='businessgroups',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='businessgroups',
            old_name='amount_currency',
            new_name='balance_currency',
        ),
    ]
