# Generated by Django 3.0.8 on 2020-07-19 20:49

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20200719_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='businessgroups',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='categories',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', editable=False, max_digits=14),
        ),
    ]
