# Generated by Django 3.0.8 on 2020-07-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20200719_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='amount_currency',
            new_name='balance_currency',
        ),
    ]
