# Generated by Django 3.0.8 on 2020-07-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20200719_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='businessgroups',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='balance_currency',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='businessgroups',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='categories',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
